# Generated by Django 5.0.7 on 2024-07-28 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disscord_servers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('account_created_on', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
                ('contact_number', models.CharField(max_length=10)),
                ('email_id', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ServerMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('MODERATOR', 'Moderator')], default='Member', max_length=20)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_of_server', to='disscord_servers.server')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'server')},
            },
        ),
    ]
